### PR TITLE
Added GitHub action to build, test, and document

### PR DESCRIPTION
**Pull request by lohedges**
This GitHub action tests that the MetaWards package can be built and installed, then runs the tests.

The build is run on the `ubuntu:latest` image, which requires the installation of `libgsl-dev` to be able to build `pygsl`. Annoyingly, it's not possible to do a single `pip` install of the Python dependencies, i.e.:

```sh
pip install cython numpy pygsl pytest
```

since `pygsl` fails to find the `numpy` package that was installed prior to it. This is why I've split the commands and installed `pygsl` separately on the line below.

### CODE REVIEW

**Comment by lohedges** [comment]
Note that the action failed because of a network timeout. Annoyingly it is not possible to manually re-run them. I previously tested this in the `feature-action` branch (with another trigger for that branch) and it works fine.

**Comment by lohedges** [comment]
Actually, you can re-run. For some reason the button didn't appear for me at first. All passed now :+1:

**Comment by lohedges** [comment]
Don't merge this yet as I'm working on adding stages to autogenerate documentation and push to the gh-pages branch.

**Comment by lohedges** [comment]
Okay, there seems to be some issues with running commands in specific working directories, even though I'm using the `working-directory` directive as documented. Will continue to debug tomorrow.

**Comment by lohedges** [comment]
Regardless, the build seems to fail around 50% of the time because it fails to connect to the Ubuntu archive image. Hopefully this is just because it's busy right now (for obvious reasons) rather than the usual CI flakiness. I do tire of debugging the flipping CI!

**Comment by chryswoods** [comment]
I've left this branch open in case you want to add anything else. Feel free to delete if you are happy.

**Comment by lohedges** [comment]
Cheers. I still need to iron out a few issues with the documentation building stages. I'll open another pull request when I'm done.

**Pull request merged**
